var friendsInfo;
friendsInfo = [];
var friendInfo1;
var friendInfo2;
var friendInfo3;
var friendInfo4;
friendInfo1 = { friendName: "Alex", friendId: 101 };
friendInfo2 = { friendName: "Moji", friendId: 102 };
friendInfo3 = { friendName: "John", friendId: 103 };
friendInfo4 = { friendName: "Due", friendId: 104 };
friendsInfo.push(friendInfo1);
friendsInfo.push(friendInfo2);
friendsInfo.push(friendInfo3);
friendsInfo.push(friendInfo4);
var getRequest2;
var postRequest2;
var putRequest2;
getRequest2 = "GET";
postRequest2 = "POST";
putRequest2 = "PUT";
console.log("getRequest2: ".concat(getRequest2, ", postRequest2: ").concat(postRequest2, ",putRequest2:").concat(putRequest2));
