var usersInfo;
usersInfo = [];
var userInfo1;
var userInfo2;
var userInfo3;
userInfo1 = { userName: "surnaly", userId: 101 };
userInfo2 = { userName: "Tisha", userId: 102 };
userInfo3 = { userName: "Rita", userId: 103 };
usersInfo.push(userInfo1);
usersInfo.push(userInfo2);
usersInfo.push(userInfo3);
var booksInfo;
booksInfo = [];
var bookInfo1;
var bookInfo2;
var bookInfo3;
var bookInfo4;
bookInfo1 = { bookName: "Poor Dad rich Dad", bookId: 101 };
bookInfo2 = { bookName: "Thank and grow rich", bookId: 102 };
bookInfo3 = { bookName: "Happiness", bookId: 103 };
bookInfo4 = { bookName: "Goal", bookId: 104 };
booksInfo.push(bookInfo1);
booksInfo.push(bookInfo2);
booksInfo.push(bookInfo3);
booksInfo.push(bookInfo4);
var getRequest;
getRequest = "POST";
var requestHandler = function (requestType) {
    console.log(requestType);
};
requestHandler("GET");
